# Generated by Django 4.2.30 on 2026-08-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('language_name', models.CharField(default='English', max_length=50)),
                ('slow', models.BooleanField(default=False)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('file_size', models.CharField(default='0 KB', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
